cloudsearch/urls.py
from django.conf.urls import url

from cloudsearch import views

urlpatterns = [
    url(r'^$', views.search, name='search'),
]

medcloud/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.contrib import admin


urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^signup/', include('register.urls', namespace='register'), ),
]

register/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from register import views

urlpatterns = [
    url(r'^$', views.register, name='register'),
    url(r'^forgotten/$', views.forgotten, name='forgotten'),
    url(r'^thanks/$', TemplateView.as_view(template_name='register/thanks.html'), name='thanks'),
]

cloudsearch/views.py
# -*- coding: utf-8  -*-
from django import forms
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from cloudsearch.utils import search_index


class SearchForm(forms.Form):
    term = forms.CharField(label=u'العبارة', max_length=100)

@csrf_exempt
def search(request):
    if request.method == 'GET':
        if 'term' in request.GET:
            form = SearchForm(request.GET)
            if form.is_valid():
                term = form.cleaned_data['term']
                results = search_index(term)
                context = {'form': form, 'results': results, 'term': term}
                return render(request, 'cloudsearch/results.html', context)
            else:
                context = {'form': form}
        else:
            form = SearchForm()
            context = {'form': form}

    return render(request, 'cloudsearch/search.html', context)

cloudsearch/templates/cloudsearch/results.html
{% extends "base.html" %}{% load bootstrap3 %}
{% block title %}نتائج: {{ term }}{% endblock %}
{% block content %}
	<form action="{% url 'search' %}" method="GET" class="form">
	{% bootstrap_form form %}
		{% buttons %}
		<button type="submit" class="btn btn-primary btn-block">
		{% bootstrap_icon "ok-sign" %} ابحث
		</button>
		{% endbuttons %}
	</form>

{% if results %}
<p>عثرنا على {{ results|length }} نتيجة.</p>
	<ol style="direction:ltr;">
	{% for result in results %}
		<li><a href="https://ksauhs-med.com/public/Medical College/{{ result.0|urlencode }}/{{ result.1|urlencode }}">{{ result.0 }}/<b>{{ result.1 }}</b></a></li>
	{% endfor %}
	</ol>
{% else %}
	<p class="alert alter-warning">لم يعثر على أي نتائج</p>
{% endif %}

{% endblock %}

cloudsearch/templates/cloudsearch/search.html
{% extends "base.html" %}{% load bootstrap3 %}
{% block title %}ابحث{% endblock %}
{% block content %}
	<div class="mnote">
		<p><b>السحابة الطبية</b> مكتبة تعاونية لطلاب كلية الطب في جامعة الملك سعود بن عبد العزيز للعلوم الصحية. يشترك الطلاب والطالبات من مختلف الأقسام والدفعات في جمع المحاضرات والكتب والفيديوهات والتطبيقات المفيدة، لتكون مرجعا شاملا متكاملا. <a href="{% url 'register:register' %}">سجّل</a> أو <a href="https://ksauhs-med.com">ادخل</a> أو <a href="http://public.ksauhs-med.com/">تصفّح</a>.</p>
	</div>
	<p class="alert alert-info">من خلال مربّع البحث هذا يمكنك البحث في محتويات السحابة الطبيّة. قد تحتاج الملفات المضافة حديثا ساعة على الأكثر لتظهر في البحث.</p>
	<form action="{% url 'search' %}" method="GET" class="form">
	{% bootstrap_form form %}
		{% buttons %}
		<button type="submit" class="btn btn-primary btn-block">
		{% bootstrap_icon "ok-sign" %} ابحث
		</button>
		{% endbuttons %}
	</form>
{% endblock %}